// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BackPack.proto

package com.huyu.protobuf;

public final class BackPackProto {
  private BackPackProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BackPackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BackPack)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 type = 1;</code>
     */
    int getType();

    /**
     * <code>string backpack_id = 2;</code>
     */
    String getBackpackId();
    /**
     * <code>string backpack_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getBackpackIdBytes();

    /**
     * <code>repeated .Prop prop = 3;</code>
     */
    java.util.List<Prop>
        getPropList();
    /**
     * <code>repeated .Prop prop = 3;</code>
     */
    BackPackProto.Prop getProp(int index);
    /**
     * <code>repeated .Prop prop = 3;</code>
     */
    int getPropCount();
    /**
     * <code>repeated .Prop prop = 3;</code>
     */
    java.util.List<? extends PropOrBuilder>
        getPropOrBuilderList();
    /**
     * <code>repeated .Prop prop = 3;</code>
     */
    BackPackProto.PropOrBuilder getPropOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code BackPack}
   */
  public  static final class BackPack extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BackPack)
      BackPackOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BackPack.newBuilder() to construct.
    private BackPack(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BackPack() {
      type_ = 0;
      backpackId_ = "";
      prop_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BackPack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              backpackId_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                prop_ = new java.util.ArrayList<Prop>();
                mutable_bitField0_ |= 0x00000004;
              }
              prop_.add(
                  input.readMessage(BackPackProto.Prop.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          prop_ = java.util.Collections.unmodifiableList(prop_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BackPackProto.internal_static_BackPack_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BackPackProto.internal_static_BackPack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BackPackProto.BackPack.class, BackPackProto.BackPack.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int BACKPACK_ID_FIELD_NUMBER = 2;
    private volatile Object backpackId_;
    /**
     * <code>string backpack_id = 2;</code>
     */
    public String getBackpackId() {
      Object ref = backpackId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        backpackId_ = s;
        return s;
      }
    }
    /**
     * <code>string backpack_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBackpackIdBytes() {
      Object ref = backpackId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        backpackId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROP_FIELD_NUMBER = 3;
    private java.util.List<Prop> prop_;
    /**
     * <code>repeated .Prop prop = 3;</code>
     */
    public java.util.List<Prop> getPropList() {
      return prop_;
    }
    /**
     * <code>repeated .Prop prop = 3;</code>
     */
    public java.util.List<? extends PropOrBuilder>
        getPropOrBuilderList() {
      return prop_;
    }
    /**
     * <code>repeated .Prop prop = 3;</code>
     */
    public int getPropCount() {
      return prop_.size();
    }
    /**
     * <code>repeated .Prop prop = 3;</code>
     */
    public BackPackProto.Prop getProp(int index) {
      return prop_.get(index);
    }
    /**
     * <code>repeated .Prop prop = 3;</code>
     */
    public BackPackProto.PropOrBuilder getPropOrBuilder(
        int index) {
      return prop_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (!getBackpackIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, backpackId_);
      }
      for (int i = 0; i < prop_.size(); i++) {
        output.writeMessage(3, prop_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (!getBackpackIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, backpackId_);
      }
      for (int i = 0; i < prop_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, prop_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BackPackProto.BackPack)) {
        return super.equals(obj);
      }
      BackPackProto.BackPack other = (BackPackProto.BackPack) obj;

      boolean result = true;
      result = result && (getType()
          == other.getType());
      result = result && getBackpackId()
          .equals(other.getBackpackId());
      result = result && getPropList()
          .equals(other.getPropList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + BACKPACK_ID_FIELD_NUMBER;
      hash = (53 * hash) + getBackpackId().hashCode();
      if (getPropCount() > 0) {
        hash = (37 * hash) + PROP_FIELD_NUMBER;
        hash = (53 * hash) + getPropList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BackPackProto.BackPack parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BackPackProto.BackPack parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BackPackProto.BackPack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BackPackProto.BackPack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BackPackProto.BackPack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BackPackProto.BackPack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BackPackProto.BackPack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BackPackProto.BackPack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BackPackProto.BackPack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BackPackProto.BackPack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BackPackProto.BackPack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BackPackProto.BackPack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BackPackProto.BackPack prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BackPack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BackPack)
        BackPackProto.BackPackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BackPackProto.internal_static_BackPack_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BackPackProto.internal_static_BackPack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BackPackProto.BackPack.class, BackPackProto.BackPack.Builder.class);
      }

      // Construct using com.huyu.protobuf.BackPackProto.BackPack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPropFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        backpackId_ = "";

        if (propBuilder_ == null) {
          prop_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          propBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BackPackProto.internal_static_BackPack_descriptor;
      }

      public BackPackProto.BackPack getDefaultInstanceForType() {
        return BackPackProto.BackPack.getDefaultInstance();
      }

      public BackPackProto.BackPack build() {
        BackPackProto.BackPack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BackPackProto.BackPack buildPartial() {
        BackPackProto.BackPack result = new BackPackProto.BackPack(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        result.backpackId_ = backpackId_;
        if (propBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            prop_ = java.util.Collections.unmodifiableList(prop_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.prop_ = prop_;
        } else {
          result.prop_ = propBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BackPackProto.BackPack) {
          return mergeFrom((BackPackProto.BackPack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BackPackProto.BackPack other) {
        if (other == BackPackProto.BackPack.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getBackpackId().isEmpty()) {
          backpackId_ = other.backpackId_;
          onChanged();
        }
        if (propBuilder_ == null) {
          if (!other.prop_.isEmpty()) {
            if (prop_.isEmpty()) {
              prop_ = other.prop_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePropIsMutable();
              prop_.addAll(other.prop_);
            }
            onChanged();
          }
        } else {
          if (!other.prop_.isEmpty()) {
            if (propBuilder_.isEmpty()) {
              propBuilder_.dispose();
              propBuilder_ = null;
              prop_ = other.prop_;
              bitField0_ = (bitField0_ & ~0x00000004);
              propBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPropFieldBuilder() : null;
            } else {
              propBuilder_.addAllMessages(other.prop_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BackPackProto.BackPack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BackPackProto.BackPack) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <code>int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 1;</code>
       */
      public Builder setType(int value) {

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 1;</code>
       */
      public Builder clearType() {

        type_ = 0;
        onChanged();
        return this;
      }

      private Object backpackId_ = "";
      /**
       * <code>string backpack_id = 2;</code>
       */
      public String getBackpackId() {
        Object ref = backpackId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          backpackId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string backpack_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBackpackIdBytes() {
        Object ref = backpackId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          backpackId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string backpack_id = 2;</code>
       */
      public Builder setBackpackId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        backpackId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string backpack_id = 2;</code>
       */
      public Builder clearBackpackId() {

        backpackId_ = getDefaultInstance().getBackpackId();
        onChanged();
        return this;
      }
      /**
       * <code>string backpack_id = 2;</code>
       */
      public Builder setBackpackIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        backpackId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Prop> prop_ =
        java.util.Collections.emptyList();
      private void ensurePropIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          prop_ = new java.util.ArrayList<Prop>(prop_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Prop, Prop.Builder, PropOrBuilder> propBuilder_;

      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public java.util.List<Prop> getPropList() {
        if (propBuilder_ == null) {
          return java.util.Collections.unmodifiableList(prop_);
        } else {
          return propBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public int getPropCount() {
        if (propBuilder_ == null) {
          return prop_.size();
        } else {
          return propBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public BackPackProto.Prop getProp(int index) {
        if (propBuilder_ == null) {
          return prop_.get(index);
        } else {
          return propBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public Builder setProp(
          int index, BackPackProto.Prop value) {
        if (propBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropIsMutable();
          prop_.set(index, value);
          onChanged();
        } else {
          propBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public Builder setProp(
          int index, BackPackProto.Prop.Builder builderForValue) {
        if (propBuilder_ == null) {
          ensurePropIsMutable();
          prop_.set(index, builderForValue.build());
          onChanged();
        } else {
          propBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public Builder addProp(BackPackProto.Prop value) {
        if (propBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropIsMutable();
          prop_.add(value);
          onChanged();
        } else {
          propBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public Builder addProp(
          int index, BackPackProto.Prop value) {
        if (propBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropIsMutable();
          prop_.add(index, value);
          onChanged();
        } else {
          propBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public Builder addProp(
          BackPackProto.Prop.Builder builderForValue) {
        if (propBuilder_ == null) {
          ensurePropIsMutable();
          prop_.add(builderForValue.build());
          onChanged();
        } else {
          propBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public Builder addProp(
          int index, BackPackProto.Prop.Builder builderForValue) {
        if (propBuilder_ == null) {
          ensurePropIsMutable();
          prop_.add(index, builderForValue.build());
          onChanged();
        } else {
          propBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public Builder addAllProp(
          Iterable<? extends Prop> values) {
        if (propBuilder_ == null) {
          ensurePropIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, prop_);
          onChanged();
        } else {
          propBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public Builder clearProp() {
        if (propBuilder_ == null) {
          prop_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          propBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public Builder removeProp(int index) {
        if (propBuilder_ == null) {
          ensurePropIsMutable();
          prop_.remove(index);
          onChanged();
        } else {
          propBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public BackPackProto.Prop.Builder getPropBuilder(
          int index) {
        return getPropFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public BackPackProto.PropOrBuilder getPropOrBuilder(
          int index) {
        if (propBuilder_ == null) {
          return prop_.get(index);  } else {
          return propBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public java.util.List<? extends PropOrBuilder>
           getPropOrBuilderList() {
        if (propBuilder_ != null) {
          return propBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(prop_);
        }
      }
      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public BackPackProto.Prop.Builder addPropBuilder() {
        return getPropFieldBuilder().addBuilder(
            BackPackProto.Prop.getDefaultInstance());
      }
      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public BackPackProto.Prop.Builder addPropBuilder(
          int index) {
        return getPropFieldBuilder().addBuilder(
            index, BackPackProto.Prop.getDefaultInstance());
      }
      /**
       * <code>repeated .Prop prop = 3;</code>
       */
      public java.util.List<Prop.Builder>
           getPropBuilderList() {
        return getPropFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Prop, Prop.Builder, PropOrBuilder>
          getPropFieldBuilder() {
        if (propBuilder_ == null) {
          propBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Prop, Prop.Builder, PropOrBuilder>(
                  prop_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          prop_ = null;
        }
        return propBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BackPack)
    }

    // @@protoc_insertion_point(class_scope:BackPack)
    private static final BackPackProto.BackPack DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BackPackProto.BackPack();
    }

    public static BackPackProto.BackPack getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BackPack>
        PARSER = new com.google.protobuf.AbstractParser<BackPack>() {
      public BackPack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BackPack(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BackPack> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BackPack> getParserForType() {
      return PARSER;
    }

    public BackPackProto.BackPack getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PropOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Prop)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 prop_id = 1;</code>
     */
    int getPropId();

    /**
     * <code>string prop_name = 2;</code>
     */
    String getPropName();
    /**
     * <code>string prop_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getPropNameBytes();
  }
  /**
   * Protobuf type {@code Prop}
   */
  public  static final class Prop extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Prop)
      PropOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Prop.newBuilder() to construct.
    private Prop(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Prop() {
      propId_ = 0;
      propName_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Prop(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              propId_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              propName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BackPackProto.internal_static_Prop_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BackPackProto.internal_static_Prop_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BackPackProto.Prop.class, BackPackProto.Prop.Builder.class);
    }

    public static final int PROP_ID_FIELD_NUMBER = 1;
    private int propId_;
    /**
     * <code>int32 prop_id = 1;</code>
     */
    public int getPropId() {
      return propId_;
    }

    public static final int PROP_NAME_FIELD_NUMBER = 2;
    private volatile Object propName_;
    /**
     * <code>string prop_name = 2;</code>
     */
    public String getPropName() {
      Object ref = propName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        propName_ = s;
        return s;
      }
    }
    /**
     * <code>string prop_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPropNameBytes() {
      Object ref = propName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        propName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (propId_ != 0) {
        output.writeInt32(1, propId_);
      }
      if (!getPropNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, propName_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (propId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, propId_);
      }
      if (!getPropNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, propName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BackPackProto.Prop)) {
        return super.equals(obj);
      }
      BackPackProto.Prop other = (BackPackProto.Prop) obj;

      boolean result = true;
      result = result && (getPropId()
          == other.getPropId());
      result = result && getPropName()
          .equals(other.getPropName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPropId();
      hash = (37 * hash) + PROP_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getPropName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BackPackProto.Prop parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BackPackProto.Prop parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BackPackProto.Prop parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BackPackProto.Prop parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BackPackProto.Prop parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BackPackProto.Prop parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BackPackProto.Prop parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BackPackProto.Prop parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BackPackProto.Prop parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BackPackProto.Prop parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BackPackProto.Prop parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BackPackProto.Prop parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BackPackProto.Prop prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Prop}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Prop)
        BackPackProto.PropOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BackPackProto.internal_static_Prop_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BackPackProto.internal_static_Prop_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BackPackProto.Prop.class, BackPackProto.Prop.Builder.class);
      }

      // Construct using com.huyu.protobuf.BackPackProto.Prop.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        propId_ = 0;

        propName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BackPackProto.internal_static_Prop_descriptor;
      }

      public BackPackProto.Prop getDefaultInstanceForType() {
        return BackPackProto.Prop.getDefaultInstance();
      }

      public BackPackProto.Prop build() {
        BackPackProto.Prop result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BackPackProto.Prop buildPartial() {
        BackPackProto.Prop result = new BackPackProto.Prop(this);
        result.propId_ = propId_;
        result.propName_ = propName_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BackPackProto.Prop) {
          return mergeFrom((BackPackProto.Prop)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BackPackProto.Prop other) {
        if (other == BackPackProto.Prop.getDefaultInstance()) return this;
        if (other.getPropId() != 0) {
          setPropId(other.getPropId());
        }
        if (!other.getPropName().isEmpty()) {
          propName_ = other.propName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BackPackProto.Prop parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BackPackProto.Prop) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int propId_ ;
      /**
       * <code>int32 prop_id = 1;</code>
       */
      public int getPropId() {
        return propId_;
      }
      /**
       * <code>int32 prop_id = 1;</code>
       */
      public Builder setPropId(int value) {

        propId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 prop_id = 1;</code>
       */
      public Builder clearPropId() {

        propId_ = 0;
        onChanged();
        return this;
      }

      private Object propName_ = "";
      /**
       * <code>string prop_name = 2;</code>
       */
      public String getPropName() {
        Object ref = propName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          propName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string prop_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPropNameBytes() {
        Object ref = propName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          propName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string prop_name = 2;</code>
       */
      public Builder setPropName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        propName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string prop_name = 2;</code>
       */
      public Builder clearPropName() {

        propName_ = getDefaultInstance().getPropName();
        onChanged();
        return this;
      }
      /**
       * <code>string prop_name = 2;</code>
       */
      public Builder setPropNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        propName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Prop)
    }

    // @@protoc_insertion_point(class_scope:Prop)
    private static final BackPackProto.Prop DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BackPackProto.Prop();
    }

    public static BackPackProto.Prop getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Prop>
        PARSER = new com.google.protobuf.AbstractParser<Prop>() {
      public Prop parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Prop(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Prop> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Prop> getParserForType() {
      return PARSER;
    }

    public BackPackProto.Prop getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BackPack_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BackPack_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Prop_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Prop_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016BackPack.proto\"B\n\010BackPack\022\014\n\004type\030\001 \001" +
      "(\005\022\023\n\013backpack_id\030\002 \001(\t\022\023\n\004prop\030\003 \003(\0132\005." +
      "Prop\"*\n\004Prop\022\017\n\007prop_id\030\001 \001(\005\022\021\n\tprop_na" +
      "me\030\002 \001(\tB\"\n\021com.huyu.protobufB\rBackPackP" +
      "rotob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BackPack_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BackPack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BackPack_descriptor,
        new String[] { "Type", "BackpackId", "Prop", });
    internal_static_Prop_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Prop_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Prop_descriptor,
        new String[] { "PropId", "PropName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
