// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommandReq.proto

package com.huyu.protobuf;

public final class CommandReqProto {
  private CommandReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommandReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CommandReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 command_sign = 1;</code>
     */
    int getCommandSign();

    /**
     * <code>string player_name = 2;</code>
     */
    String getPlayerName();
    /**
     * <code>string player_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getPlayerNameBytes();

    /**
     * <code>string command_name = 3;</code>
     */
    String getCommandName();
    /**
     * <code>string command_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getCommandNameBytes();

    /**
     * <code>repeated string option = 4;</code>
     */
    java.util.List<String>
        getOptionList();
    /**
     * <code>repeated string option = 4;</code>
     */
    int getOptionCount();
    /**
     * <code>repeated string option = 4;</code>
     */
    String getOption(int index);
    /**
     * <code>repeated string option = 4;</code>
     */
    com.google.protobuf.ByteString
        getOptionBytes(int index);
  }
  /**
   * Protobuf type {@code CommandReq}
   */
  public  static final class CommandReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CommandReq)
      CommandReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommandReq.newBuilder() to construct.
    private CommandReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommandReq() {
      commandSign_ = 0;
      playerName_ = "";
      commandName_ = "";
      option_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommandReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              commandSign_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              playerName_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              commandName_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                option_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              option_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          option_ = option_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CommandReqProto.internal_static_CommandReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CommandReqProto.internal_static_CommandReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CommandReqProto.CommandReq.class, CommandReqProto.CommandReq.Builder.class);
    }

    private int bitField0_;
    public static final int COMMAND_SIGN_FIELD_NUMBER = 1;
    private int commandSign_;
    /**
     * <code>int32 command_sign = 1;</code>
     */
    public int getCommandSign() {
      return commandSign_;
    }

    public static final int PLAYER_NAME_FIELD_NUMBER = 2;
    private volatile Object playerName_;
    /**
     * <code>string player_name = 2;</code>
     */
    public String getPlayerName() {
      Object ref = playerName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        playerName_ = s;
        return s;
      }
    }
    /**
     * <code>string player_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerNameBytes() {
      Object ref = playerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        playerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMAND_NAME_FIELD_NUMBER = 3;
    private volatile Object commandName_;
    /**
     * <code>string command_name = 3;</code>
     */
    public String getCommandName() {
      Object ref = commandName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        commandName_ = s;
        return s;
      }
    }
    /**
     * <code>string command_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCommandNameBytes() {
      Object ref = commandName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        commandName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPTION_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList option_;
    /**
     * <code>repeated string option = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getOptionList() {
      return option_;
    }
    /**
     * <code>repeated string option = 4;</code>
     */
    public int getOptionCount() {
      return option_.size();
    }
    /**
     * <code>repeated string option = 4;</code>
     */
    public String getOption(int index) {
      return option_.get(index);
    }
    /**
     * <code>repeated string option = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOptionBytes(int index) {
      return option_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (commandSign_ != 0) {
        output.writeInt32(1, commandSign_);
      }
      if (!getPlayerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, playerName_);
      }
      if (!getCommandNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, commandName_);
      }
      for (int i = 0; i < option_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, option_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (commandSign_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, commandSign_);
      }
      if (!getPlayerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, playerName_);
      }
      if (!getCommandNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, commandName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < option_.size(); i++) {
          dataSize += computeStringSizeNoTag(option_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getOptionList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CommandReqProto.CommandReq)) {
        return super.equals(obj);
      }
      CommandReqProto.CommandReq other = (CommandReqProto.CommandReq) obj;

      boolean result = true;
      result = result && (getCommandSign()
          == other.getCommandSign());
      result = result && getPlayerName()
          .equals(other.getPlayerName());
      result = result && getCommandName()
          .equals(other.getCommandName());
      result = result && getOptionList()
          .equals(other.getOptionList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMAND_SIGN_FIELD_NUMBER;
      hash = (53 * hash) + getCommandSign();
      hash = (37 * hash) + PLAYER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerName().hashCode();
      hash = (37 * hash) + COMMAND_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getCommandName().hashCode();
      if (getOptionCount() > 0) {
        hash = (37 * hash) + OPTION_FIELD_NUMBER;
        hash = (53 * hash) + getOptionList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CommandReqProto.CommandReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommandReqProto.CommandReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommandReqProto.CommandReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommandReqProto.CommandReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommandReqProto.CommandReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommandReqProto.CommandReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommandReqProto.CommandReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CommandReqProto.CommandReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CommandReqProto.CommandReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CommandReqProto.CommandReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CommandReqProto.CommandReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CommandReqProto.CommandReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CommandReqProto.CommandReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommandReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CommandReq)
        CommandReqProto.CommandReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CommandReqProto.internal_static_CommandReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CommandReqProto.internal_static_CommandReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CommandReqProto.CommandReq.class, CommandReqProto.CommandReq.Builder.class);
      }

      // Construct using com.huyu.protobuf.CommandReqProto.CommandReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        commandSign_ = 0;

        playerName_ = "";

        commandName_ = "";

        option_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CommandReqProto.internal_static_CommandReq_descriptor;
      }

      public CommandReqProto.CommandReq getDefaultInstanceForType() {
        return CommandReqProto.CommandReq.getDefaultInstance();
      }

      public CommandReqProto.CommandReq build() {
        CommandReqProto.CommandReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CommandReqProto.CommandReq buildPartial() {
        CommandReqProto.CommandReq result = new CommandReqProto.CommandReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.commandSign_ = commandSign_;
        result.playerName_ = playerName_;
        result.commandName_ = commandName_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          option_ = option_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.option_ = option_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CommandReqProto.CommandReq) {
          return mergeFrom((CommandReqProto.CommandReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CommandReqProto.CommandReq other) {
        if (other == CommandReqProto.CommandReq.getDefaultInstance()) return this;
        if (other.getCommandSign() != 0) {
          setCommandSign(other.getCommandSign());
        }
        if (!other.getPlayerName().isEmpty()) {
          playerName_ = other.playerName_;
          onChanged();
        }
        if (!other.getCommandName().isEmpty()) {
          commandName_ = other.commandName_;
          onChanged();
        }
        if (!other.option_.isEmpty()) {
          if (option_.isEmpty()) {
            option_ = other.option_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureOptionIsMutable();
            option_.addAll(other.option_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CommandReqProto.CommandReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CommandReqProto.CommandReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int commandSign_ ;
      /**
       * <code>int32 command_sign = 1;</code>
       */
      public int getCommandSign() {
        return commandSign_;
      }
      /**
       * <code>int32 command_sign = 1;</code>
       */
      public Builder setCommandSign(int value) {

        commandSign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 command_sign = 1;</code>
       */
      public Builder clearCommandSign() {

        commandSign_ = 0;
        onChanged();
        return this;
      }

      private Object playerName_ = "";
      /**
       * <code>string player_name = 2;</code>
       */
      public String getPlayerName() {
        Object ref = playerName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          playerName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string player_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerNameBytes() {
        Object ref = playerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          playerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string player_name = 2;</code>
       */
      public Builder setPlayerName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        playerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string player_name = 2;</code>
       */
      public Builder clearPlayerName() {

        playerName_ = getDefaultInstance().getPlayerName();
        onChanged();
        return this;
      }
      /**
       * <code>string player_name = 2;</code>
       */
      public Builder setPlayerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        playerName_ = value;
        onChanged();
        return this;
      }

      private Object commandName_ = "";
      /**
       * <code>string command_name = 3;</code>
       */
      public String getCommandName() {
        Object ref = commandName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          commandName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string command_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCommandNameBytes() {
        Object ref = commandName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          commandName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string command_name = 3;</code>
       */
      public Builder setCommandName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        commandName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string command_name = 3;</code>
       */
      public Builder clearCommandName() {

        commandName_ = getDefaultInstance().getCommandName();
        onChanged();
        return this;
      }
      /**
       * <code>string command_name = 3;</code>
       */
      public Builder setCommandNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        commandName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList option_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureOptionIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          option_ = new com.google.protobuf.LazyStringArrayList(option_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string option = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getOptionList() {
        return option_.getUnmodifiableView();
      }
      /**
       * <code>repeated string option = 4;</code>
       */
      public int getOptionCount() {
        return option_.size();
      }
      /**
       * <code>repeated string option = 4;</code>
       */
      public String getOption(int index) {
        return option_.get(index);
      }
      /**
       * <code>repeated string option = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOptionBytes(int index) {
        return option_.getByteString(index);
      }
      /**
       * <code>repeated string option = 4;</code>
       */
      public Builder setOption(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOptionIsMutable();
        option_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string option = 4;</code>
       */
      public Builder addOption(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOptionIsMutable();
        option_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string option = 4;</code>
       */
      public Builder addAllOption(
          Iterable<String> values) {
        ensureOptionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, option_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string option = 4;</code>
       */
      public Builder clearOption() {
        option_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string option = 4;</code>
       */
      public Builder addOptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureOptionIsMutable();
        option_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CommandReq)
    }

    // @@protoc_insertion_point(class_scope:CommandReq)
    private static final CommandReqProto.CommandReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CommandReqProto.CommandReq();
    }

    public static CommandReqProto.CommandReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommandReq>
        PARSER = new com.google.protobuf.AbstractParser<CommandReq>() {
      public CommandReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommandReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommandReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CommandReq> getParserForType() {
      return PARSER;
    }

    public CommandReqProto.CommandReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommandReq_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommandReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020CommandReq.proto\"]\n\nCommandReq\022\024\n\014comm" +
      "and_sign\030\001 \001(\005\022\023\n\013player_name\030\002 \001(\t\022\024\n\014c" +
      "ommand_name\030\003 \001(\t\022\016\n\006option\030\004 \003(\tB$\n\021com" +
      ".huyu.protobufB\017CommandReqProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CommandReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CommandReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommandReq_descriptor,
        new String[] { "CommandSign", "PlayerName", "CommandName", "Option", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
