// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonsterResp.proto

package com.huyu.protobuf;

public final class MonsterRespProto {
  private MonsterRespProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MonsterRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MonsterResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 monster_id = 1;</code>
     */
    int getMonsterId();

    /**
     * <code>string monster_name = 2;</code>
     */
    String getMonsterName();
    /**
     * <code>string monster_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getMonsterNameBytes();

    /**
     * <code>int32 monster_blood = 3;</code>
     */
    int getMonsterBlood();

    /**
     * <code>int32 harm = 4;</code>
     */
    int getHarm();

    /**
     * <code>bool status = 5;</code>
     */
    boolean getStatus();
  }
  /**
   * Protobuf type {@code MonsterResp}
   */
  public  static final class MonsterResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MonsterResp)
      MonsterRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MonsterResp.newBuilder() to construct.
    private MonsterResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MonsterResp() {
      monsterId_ = 0;
      monsterName_ = "";
      monsterBlood_ = 0;
      harm_ = 0;
      status_ = false;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MonsterResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              monsterId_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              monsterName_ = s;
              break;
            }
            case 24: {

              monsterBlood_ = input.readInt32();
              break;
            }
            case 32: {

              harm_ = input.readInt32();
              break;
            }
            case 40: {

              status_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MonsterRespProto.internal_static_MonsterResp_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MonsterRespProto.internal_static_MonsterResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MonsterRespProto.MonsterResp.class, MonsterRespProto.MonsterResp.Builder.class);
    }

    public static final int MONSTER_ID_FIELD_NUMBER = 1;
    private int monsterId_;
    /**
     * <code>int32 monster_id = 1;</code>
     */
    public int getMonsterId() {
      return monsterId_;
    }

    public static final int MONSTER_NAME_FIELD_NUMBER = 2;
    private volatile Object monsterName_;
    /**
     * <code>string monster_name = 2;</code>
     */
    public String getMonsterName() {
      Object ref = monsterName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        monsterName_ = s;
        return s;
      }
    }
    /**
     * <code>string monster_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMonsterNameBytes() {
      Object ref = monsterName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        monsterName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MONSTER_BLOOD_FIELD_NUMBER = 3;
    private int monsterBlood_;
    /**
     * <code>int32 monster_blood = 3;</code>
     */
    public int getMonsterBlood() {
      return monsterBlood_;
    }

    public static final int HARM_FIELD_NUMBER = 4;
    private int harm_;
    /**
     * <code>int32 harm = 4;</code>
     */
    public int getHarm() {
      return harm_;
    }

    public static final int STATUS_FIELD_NUMBER = 5;
    private boolean status_;
    /**
     * <code>bool status = 5;</code>
     */
    public boolean getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (monsterId_ != 0) {
        output.writeInt32(1, monsterId_);
      }
      if (!getMonsterNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, monsterName_);
      }
      if (monsterBlood_ != 0) {
        output.writeInt32(3, monsterBlood_);
      }
      if (harm_ != 0) {
        output.writeInt32(4, harm_);
      }
      if (status_ != false) {
        output.writeBool(5, status_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (monsterId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, monsterId_);
      }
      if (!getMonsterNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, monsterName_);
      }
      if (monsterBlood_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, monsterBlood_);
      }
      if (harm_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, harm_);
      }
      if (status_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MonsterRespProto.MonsterResp)) {
        return super.equals(obj);
      }
      MonsterRespProto.MonsterResp other = (MonsterRespProto.MonsterResp) obj;

      boolean result = true;
      result = result && (getMonsterId()
          == other.getMonsterId());
      result = result && getMonsterName()
          .equals(other.getMonsterName());
      result = result && (getMonsterBlood()
          == other.getMonsterBlood());
      result = result && (getHarm()
          == other.getHarm());
      result = result && (getStatus()
          == other.getStatus());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MONSTER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMonsterId();
      hash = (37 * hash) + MONSTER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getMonsterName().hashCode();
      hash = (37 * hash) + MONSTER_BLOOD_FIELD_NUMBER;
      hash = (53 * hash) + getMonsterBlood();
      hash = (37 * hash) + HARM_FIELD_NUMBER;
      hash = (53 * hash) + getHarm();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStatus());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MonsterRespProto.MonsterResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MonsterRespProto.MonsterResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MonsterRespProto.MonsterResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MonsterRespProto.MonsterResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MonsterRespProto.MonsterResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MonsterRespProto.MonsterResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MonsterRespProto.MonsterResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MonsterRespProto.MonsterResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MonsterRespProto.MonsterResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MonsterRespProto.MonsterResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MonsterRespProto.MonsterResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MonsterRespProto.MonsterResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MonsterRespProto.MonsterResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MonsterResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MonsterResp)
        MonsterRespProto.MonsterRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MonsterRespProto.internal_static_MonsterResp_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MonsterRespProto.internal_static_MonsterResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MonsterRespProto.MonsterResp.class, MonsterRespProto.MonsterResp.Builder.class);
      }

      // Construct using com.huyu.protobuf.MonsterRespProto.MonsterResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        monsterId_ = 0;

        monsterName_ = "";

        monsterBlood_ = 0;

        harm_ = 0;

        status_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MonsterRespProto.internal_static_MonsterResp_descriptor;
      }

      public MonsterRespProto.MonsterResp getDefaultInstanceForType() {
        return MonsterRespProto.MonsterResp.getDefaultInstance();
      }

      public MonsterRespProto.MonsterResp build() {
        MonsterRespProto.MonsterResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MonsterRespProto.MonsterResp buildPartial() {
        MonsterRespProto.MonsterResp result = new MonsterRespProto.MonsterResp(this);
        result.monsterId_ = monsterId_;
        result.monsterName_ = monsterName_;
        result.monsterBlood_ = monsterBlood_;
        result.harm_ = harm_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MonsterRespProto.MonsterResp) {
          return mergeFrom((MonsterRespProto.MonsterResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MonsterRespProto.MonsterResp other) {
        if (other == MonsterRespProto.MonsterResp.getDefaultInstance()) return this;
        if (other.getMonsterId() != 0) {
          setMonsterId(other.getMonsterId());
        }
        if (!other.getMonsterName().isEmpty()) {
          monsterName_ = other.monsterName_;
          onChanged();
        }
        if (other.getMonsterBlood() != 0) {
          setMonsterBlood(other.getMonsterBlood());
        }
        if (other.getHarm() != 0) {
          setHarm(other.getHarm());
        }
        if (other.getStatus() != false) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MonsterRespProto.MonsterResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MonsterRespProto.MonsterResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int monsterId_ ;
      /**
       * <code>int32 monster_id = 1;</code>
       */
      public int getMonsterId() {
        return monsterId_;
      }
      /**
       * <code>int32 monster_id = 1;</code>
       */
      public Builder setMonsterId(int value) {

        monsterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 monster_id = 1;</code>
       */
      public Builder clearMonsterId() {

        monsterId_ = 0;
        onChanged();
        return this;
      }

      private Object monsterName_ = "";
      /**
       * <code>string monster_name = 2;</code>
       */
      public String getMonsterName() {
        Object ref = monsterName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          monsterName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string monster_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMonsterNameBytes() {
        Object ref = monsterName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          monsterName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string monster_name = 2;</code>
       */
      public Builder setMonsterName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        monsterName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string monster_name = 2;</code>
       */
      public Builder clearMonsterName() {

        monsterName_ = getDefaultInstance().getMonsterName();
        onChanged();
        return this;
      }
      /**
       * <code>string monster_name = 2;</code>
       */
      public Builder setMonsterNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        monsterName_ = value;
        onChanged();
        return this;
      }

      private int monsterBlood_ ;
      /**
       * <code>int32 monster_blood = 3;</code>
       */
      public int getMonsterBlood() {
        return monsterBlood_;
      }
      /**
       * <code>int32 monster_blood = 3;</code>
       */
      public Builder setMonsterBlood(int value) {

        monsterBlood_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 monster_blood = 3;</code>
       */
      public Builder clearMonsterBlood() {

        monsterBlood_ = 0;
        onChanged();
        return this;
      }

      private int harm_ ;
      /**
       * <code>int32 harm = 4;</code>
       */
      public int getHarm() {
        return harm_;
      }
      /**
       * <code>int32 harm = 4;</code>
       */
      public Builder setHarm(int value) {

        harm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 harm = 4;</code>
       */
      public Builder clearHarm() {

        harm_ = 0;
        onChanged();
        return this;
      }

      private boolean status_ ;
      /**
       * <code>bool status = 5;</code>
       */
      public boolean getStatus() {
        return status_;
      }
      /**
       * <code>bool status = 5;</code>
       */
      public Builder setStatus(boolean value) {

        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool status = 5;</code>
       */
      public Builder clearStatus() {

        status_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MonsterResp)
    }

    // @@protoc_insertion_point(class_scope:MonsterResp)
    private static final MonsterRespProto.MonsterResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MonsterRespProto.MonsterResp();
    }

    public static MonsterRespProto.MonsterResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MonsterResp>
        PARSER = new com.google.protobuf.AbstractParser<MonsterResp>() {
      public MonsterResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MonsterResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MonsterResp> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MonsterResp> getParserForType() {
      return PARSER;
    }

    public MonsterRespProto.MonsterResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MonsterResp_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MonsterResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021MonsterResp.proto\"l\n\013MonsterResp\022\022\n\nmo" +
      "nster_id\030\001 \001(\005\022\024\n\014monster_name\030\002 \001(\t\022\025\n\r" +
      "monster_blood\030\003 \001(\005\022\014\n\004harm\030\004 \001(\005\022\016\n\006sta" +
      "tus\030\005 \001(\010B%\n\021com.huyu.protobufB\020MonsterR" +
      "espProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MonsterResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MonsterResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MonsterResp_descriptor,
        new String[] { "MonsterId", "MonsterName", "MonsterBlood", "Harm", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
