// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NPCResp.proto

package com.huyu.protobuf;

public final class NPCRespProto {
  private NPCRespProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NPCRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NPCResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 npc_id = 1;</code>
     */
    int getNpcId();

    /**
     * <code>string npc_name = 2;</code>
     */
    String getNpcName();
    /**
     * <code>string npc_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNpcNameBytes();

    /**
     * <code>string talk = 3;</code>
     */
    String getTalk();
    /**
     * <code>string talk = 3;</code>
     */
    com.google.protobuf.ByteString
        getTalkBytes();
  }
  /**
   * Protobuf type {@code NPCResp}
   */
  public  static final class NPCResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NPCResp)
      NPCRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NPCResp.newBuilder() to construct.
    private NPCResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NPCResp() {
      npcId_ = 0;
      npcName_ = "";
      talk_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NPCResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              npcId_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              npcName_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              talk_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NPCRespProto.internal_static_NPCResp_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NPCRespProto.internal_static_NPCResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NPCRespProto.NPCResp.class, NPCRespProto.NPCResp.Builder.class);
    }

    public static final int NPC_ID_FIELD_NUMBER = 1;
    private int npcId_;
    /**
     * <code>int32 npc_id = 1;</code>
     */
    public int getNpcId() {
      return npcId_;
    }

    public static final int NPC_NAME_FIELD_NUMBER = 2;
    private volatile Object npcName_;
    /**
     * <code>string npc_name = 2;</code>
     */
    public String getNpcName() {
      Object ref = npcName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        npcName_ = s;
        return s;
      }
    }
    /**
     * <code>string npc_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNpcNameBytes() {
      Object ref = npcName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        npcName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TALK_FIELD_NUMBER = 3;
    private volatile Object talk_;
    /**
     * <code>string talk = 3;</code>
     */
    public String getTalk() {
      Object ref = talk_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        talk_ = s;
        return s;
      }
    }
    /**
     * <code>string talk = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTalkBytes() {
      Object ref = talk_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        talk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (npcId_ != 0) {
        output.writeInt32(1, npcId_);
      }
      if (!getNpcNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, npcName_);
      }
      if (!getTalkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, talk_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (npcId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, npcId_);
      }
      if (!getNpcNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, npcName_);
      }
      if (!getTalkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, talk_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NPCRespProto.NPCResp)) {
        return super.equals(obj);
      }
      NPCRespProto.NPCResp other = (NPCRespProto.NPCResp) obj;

      boolean result = true;
      result = result && (getNpcId()
          == other.getNpcId());
      result = result && getNpcName()
          .equals(other.getNpcName());
      result = result && getTalk()
          .equals(other.getTalk());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NPC_ID_FIELD_NUMBER;
      hash = (53 * hash) + getNpcId();
      hash = (37 * hash) + NPC_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getNpcName().hashCode();
      hash = (37 * hash) + TALK_FIELD_NUMBER;
      hash = (53 * hash) + getTalk().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NPCRespProto.NPCResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NPCRespProto.NPCResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NPCRespProto.NPCResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NPCRespProto.NPCResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NPCRespProto.NPCResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NPCRespProto.NPCResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NPCRespProto.NPCResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NPCRespProto.NPCResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static NPCRespProto.NPCResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static NPCRespProto.NPCResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NPCRespProto.NPCResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NPCRespProto.NPCResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NPCRespProto.NPCResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NPCResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NPCResp)
        NPCRespProto.NPCRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NPCRespProto.internal_static_NPCResp_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NPCRespProto.internal_static_NPCResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NPCRespProto.NPCResp.class, NPCRespProto.NPCResp.Builder.class);
      }

      // Construct using com.huyu.protobuf.NPCRespProto.NPCResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        npcId_ = 0;

        npcName_ = "";

        talk_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NPCRespProto.internal_static_NPCResp_descriptor;
      }

      public NPCRespProto.NPCResp getDefaultInstanceForType() {
        return NPCRespProto.NPCResp.getDefaultInstance();
      }

      public NPCRespProto.NPCResp build() {
        NPCRespProto.NPCResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NPCRespProto.NPCResp buildPartial() {
        NPCRespProto.NPCResp result = new NPCRespProto.NPCResp(this);
        result.npcId_ = npcId_;
        result.npcName_ = npcName_;
        result.talk_ = talk_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NPCRespProto.NPCResp) {
          return mergeFrom((NPCRespProto.NPCResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NPCRespProto.NPCResp other) {
        if (other == NPCRespProto.NPCResp.getDefaultInstance()) return this;
        if (other.getNpcId() != 0) {
          setNpcId(other.getNpcId());
        }
        if (!other.getNpcName().isEmpty()) {
          npcName_ = other.npcName_;
          onChanged();
        }
        if (!other.getTalk().isEmpty()) {
          talk_ = other.talk_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NPCRespProto.NPCResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NPCRespProto.NPCResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int npcId_ ;
      /**
       * <code>int32 npc_id = 1;</code>
       */
      public int getNpcId() {
        return npcId_;
      }
      /**
       * <code>int32 npc_id = 1;</code>
       */
      public Builder setNpcId(int value) {

        npcId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 npc_id = 1;</code>
       */
      public Builder clearNpcId() {

        npcId_ = 0;
        onChanged();
        return this;
      }

      private Object npcName_ = "";
      /**
       * <code>string npc_name = 2;</code>
       */
      public String getNpcName() {
        Object ref = npcName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          npcName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string npc_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNpcNameBytes() {
        Object ref = npcName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          npcName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string npc_name = 2;</code>
       */
      public Builder setNpcName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        npcName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string npc_name = 2;</code>
       */
      public Builder clearNpcName() {

        npcName_ = getDefaultInstance().getNpcName();
        onChanged();
        return this;
      }
      /**
       * <code>string npc_name = 2;</code>
       */
      public Builder setNpcNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        npcName_ = value;
        onChanged();
        return this;
      }

      private Object talk_ = "";
      /**
       * <code>string talk = 3;</code>
       */
      public String getTalk() {
        Object ref = talk_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          talk_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string talk = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTalkBytes() {
        Object ref = talk_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          talk_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string talk = 3;</code>
       */
      public Builder setTalk(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        talk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string talk = 3;</code>
       */
      public Builder clearTalk() {

        talk_ = getDefaultInstance().getTalk();
        onChanged();
        return this;
      }
      /**
       * <code>string talk = 3;</code>
       */
      public Builder setTalkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        talk_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NPCResp)
    }

    // @@protoc_insertion_point(class_scope:NPCResp)
    private static final NPCRespProto.NPCResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NPCRespProto.NPCResp();
    }

    public static NPCRespProto.NPCResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NPCResp>
        PARSER = new com.google.protobuf.AbstractParser<NPCResp>() {
      public NPCResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NPCResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NPCResp> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<NPCResp> getParserForType() {
      return PARSER;
    }

    public NPCRespProto.NPCResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NPCResp_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NPCResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rNPCResp.proto\"9\n\007NPCResp\022\016\n\006npc_id\030\001 \001" +
      "(\005\022\020\n\010npc_name\030\002 \001(\t\022\014\n\004talk\030\003 \001(\tB!\n\021co" +
      "m.huyu.protobufB\014NPCRespProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NPCResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NPCResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NPCResp_descriptor,
        new String[] { "NpcId", "NpcName", "Talk", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
