// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerResp.proto

package com.huyu.protobuf;

public final class PlayerRespProto {
  private PlayerRespProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 player_id = 1;</code>
     */
    int getPlayerId();

    /**
     * <code>string player_name = 2;</code>
     */
    String getPlayerName();
    /**
     * <code>string player_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getPlayerNameBytes();

    /**
     * <code>int32 status = 3;</code>
     */
    int getStatus();

    /**
     * <code>string scence_name = 4;</code>
     */
    String getScenceName();
    /**
     * <code>string scence_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getScenceNameBytes();

    /**
     * <code>int32 player_mp = 5;</code>
     */
    int getPlayerMp();

    /**
     * <code>int32 player_hp = 6;</code>
     */
    int getPlayerHp();

    /**
     * <code>int32 harm = 7;</code>
     */
    int getHarm();
  }
  /**
   * Protobuf type {@code PlayerResp}
   */
  public  static final class PlayerResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerResp)
      PlayerRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerResp.newBuilder() to construct.
    private PlayerResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerResp() {
      playerId_ = 0;
      playerName_ = "";
      status_ = 0;
      scenceName_ = "";
      playerMp_ = 0;
      playerHp_ = 0;
      harm_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              playerId_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              playerName_ = s;
              break;
            }
            case 24: {

              status_ = input.readInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              scenceName_ = s;
              break;
            }
            case 40: {

              playerMp_ = input.readInt32();
              break;
            }
            case 48: {

              playerHp_ = input.readInt32();
              break;
            }
            case 56: {

              harm_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PlayerRespProto.internal_static_PlayerResp_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PlayerRespProto.internal_static_PlayerResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PlayerRespProto.PlayerResp.class, PlayerRespProto.PlayerResp.Builder.class);
    }

    public static final int PLAYER_ID_FIELD_NUMBER = 1;
    private int playerId_;
    /**
     * <code>int32 player_id = 1;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    public static final int PLAYER_NAME_FIELD_NUMBER = 2;
    private volatile Object playerName_;
    /**
     * <code>string player_name = 2;</code>
     */
    public String getPlayerName() {
      Object ref = playerName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        playerName_ = s;
        return s;
      }
    }
    /**
     * <code>string player_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerNameBytes() {
      Object ref = playerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        playerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <code>int32 status = 3;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int SCENCE_NAME_FIELD_NUMBER = 4;
    private volatile Object scenceName_;
    /**
     * <code>string scence_name = 4;</code>
     */
    public String getScenceName() {
      Object ref = scenceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        scenceName_ = s;
        return s;
      }
    }
    /**
     * <code>string scence_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getScenceNameBytes() {
      Object ref = scenceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        scenceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYER_MP_FIELD_NUMBER = 5;
    private int playerMp_;
    /**
     * <code>int32 player_mp = 5;</code>
     */
    public int getPlayerMp() {
      return playerMp_;
    }

    public static final int PLAYER_HP_FIELD_NUMBER = 6;
    private int playerHp_;
    /**
     * <code>int32 player_hp = 6;</code>
     */
    public int getPlayerHp() {
      return playerHp_;
    }

    public static final int HARM_FIELD_NUMBER = 7;
    private int harm_;
    /**
     * <code>int32 harm = 7;</code>
     */
    public int getHarm() {
      return harm_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerId_ != 0) {
        output.writeInt32(1, playerId_);
      }
      if (!getPlayerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, playerName_);
      }
      if (status_ != 0) {
        output.writeInt32(3, status_);
      }
      if (!getScenceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, scenceName_);
      }
      if (playerMp_ != 0) {
        output.writeInt32(5, playerMp_);
      }
      if (playerHp_ != 0) {
        output.writeInt32(6, playerHp_);
      }
      if (harm_ != 0) {
        output.writeInt32(7, harm_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (playerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerId_);
      }
      if (!getPlayerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, playerName_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, status_);
      }
      if (!getScenceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, scenceName_);
      }
      if (playerMp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, playerMp_);
      }
      if (playerHp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, playerHp_);
      }
      if (harm_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, harm_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PlayerRespProto.PlayerResp)) {
        return super.equals(obj);
      }
      PlayerRespProto.PlayerResp other = (PlayerRespProto.PlayerResp) obj;

      boolean result = true;
      result = result && (getPlayerId()
          == other.getPlayerId());
      result = result && getPlayerName()
          .equals(other.getPlayerName());
      result = result && (getStatus()
          == other.getStatus());
      result = result && getScenceName()
          .equals(other.getScenceName());
      result = result && (getPlayerMp()
          == other.getPlayerMp());
      result = result && (getPlayerHp()
          == other.getPlayerHp());
      result = result && (getHarm()
          == other.getHarm());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerId();
      hash = (37 * hash) + PLAYER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerName().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + SCENCE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getScenceName().hashCode();
      hash = (37 * hash) + PLAYER_MP_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerMp();
      hash = (37 * hash) + PLAYER_HP_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerHp();
      hash = (37 * hash) + HARM_FIELD_NUMBER;
      hash = (53 * hash) + getHarm();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PlayerRespProto.PlayerResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerRespProto.PlayerResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerRespProto.PlayerResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerRespProto.PlayerResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerRespProto.PlayerResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerRespProto.PlayerResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerRespProto.PlayerResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlayerRespProto.PlayerResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlayerRespProto.PlayerResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PlayerRespProto.PlayerResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlayerRespProto.PlayerResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlayerRespProto.PlayerResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PlayerRespProto.PlayerResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerResp)
        PlayerRespProto.PlayerRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PlayerRespProto.internal_static_PlayerResp_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PlayerRespProto.internal_static_PlayerResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PlayerRespProto.PlayerResp.class, PlayerRespProto.PlayerResp.Builder.class);
      }

      // Construct using com.huyu.protobuf.PlayerRespProto.PlayerResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        playerId_ = 0;

        playerName_ = "";

        status_ = 0;

        scenceName_ = "";

        playerMp_ = 0;

        playerHp_ = 0;

        harm_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PlayerRespProto.internal_static_PlayerResp_descriptor;
      }

      public PlayerRespProto.PlayerResp getDefaultInstanceForType() {
        return PlayerRespProto.PlayerResp.getDefaultInstance();
      }

      public PlayerRespProto.PlayerResp build() {
        PlayerRespProto.PlayerResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PlayerRespProto.PlayerResp buildPartial() {
        PlayerRespProto.PlayerResp result = new PlayerRespProto.PlayerResp(this);
        result.playerId_ = playerId_;
        result.playerName_ = playerName_;
        result.status_ = status_;
        result.scenceName_ = scenceName_;
        result.playerMp_ = playerMp_;
        result.playerHp_ = playerHp_;
        result.harm_ = harm_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PlayerRespProto.PlayerResp) {
          return mergeFrom((PlayerRespProto.PlayerResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PlayerRespProto.PlayerResp other) {
        if (other == PlayerRespProto.PlayerResp.getDefaultInstance()) return this;
        if (other.getPlayerId() != 0) {
          setPlayerId(other.getPlayerId());
        }
        if (!other.getPlayerName().isEmpty()) {
          playerName_ = other.playerName_;
          onChanged();
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getScenceName().isEmpty()) {
          scenceName_ = other.scenceName_;
          onChanged();
        }
        if (other.getPlayerMp() != 0) {
          setPlayerMp(other.getPlayerMp());
        }
        if (other.getPlayerHp() != 0) {
          setPlayerHp(other.getPlayerHp());
        }
        if (other.getHarm() != 0) {
          setHarm(other.getHarm());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PlayerRespProto.PlayerResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PlayerRespProto.PlayerResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int playerId_ ;
      /**
       * <code>int32 player_id = 1;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>int32 player_id = 1;</code>
       */
      public Builder setPlayerId(int value) {

        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 player_id = 1;</code>
       */
      public Builder clearPlayerId() {

        playerId_ = 0;
        onChanged();
        return this;
      }

      private Object playerName_ = "";
      /**
       * <code>string player_name = 2;</code>
       */
      public String getPlayerName() {
        Object ref = playerName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          playerName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string player_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerNameBytes() {
        Object ref = playerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          playerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string player_name = 2;</code>
       */
      public Builder setPlayerName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        playerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string player_name = 2;</code>
       */
      public Builder clearPlayerName() {

        playerName_ = getDefaultInstance().getPlayerName();
        onChanged();
        return this;
      }
      /**
       * <code>string player_name = 2;</code>
       */
      public Builder setPlayerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        playerName_ = value;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 3;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 3;</code>
       */
      public Builder setStatus(int value) {

        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 3;</code>
       */
      public Builder clearStatus() {

        status_ = 0;
        onChanged();
        return this;
      }

      private Object scenceName_ = "";
      /**
       * <code>string scence_name = 4;</code>
       */
      public String getScenceName() {
        Object ref = scenceName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          scenceName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string scence_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getScenceNameBytes() {
        Object ref = scenceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          scenceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string scence_name = 4;</code>
       */
      public Builder setScenceName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        scenceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string scence_name = 4;</code>
       */
      public Builder clearScenceName() {

        scenceName_ = getDefaultInstance().getScenceName();
        onChanged();
        return this;
      }
      /**
       * <code>string scence_name = 4;</code>
       */
      public Builder setScenceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        scenceName_ = value;
        onChanged();
        return this;
      }

      private int playerMp_ ;
      /**
       * <code>int32 player_mp = 5;</code>
       */
      public int getPlayerMp() {
        return playerMp_;
      }
      /**
       * <code>int32 player_mp = 5;</code>
       */
      public Builder setPlayerMp(int value) {

        playerMp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 player_mp = 5;</code>
       */
      public Builder clearPlayerMp() {

        playerMp_ = 0;
        onChanged();
        return this;
      }

      private int playerHp_ ;
      /**
       * <code>int32 player_hp = 6;</code>
       */
      public int getPlayerHp() {
        return playerHp_;
      }
      /**
       * <code>int32 player_hp = 6;</code>
       */
      public Builder setPlayerHp(int value) {

        playerHp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 player_hp = 6;</code>
       */
      public Builder clearPlayerHp() {

        playerHp_ = 0;
        onChanged();
        return this;
      }

      private int harm_ ;
      /**
       * <code>int32 harm = 7;</code>
       */
      public int getHarm() {
        return harm_;
      }
      /**
       * <code>int32 harm = 7;</code>
       */
      public Builder setHarm(int value) {

        harm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 harm = 7;</code>
       */
      public Builder clearHarm() {

        harm_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PlayerResp)
    }

    // @@protoc_insertion_point(class_scope:PlayerResp)
    private static final PlayerRespProto.PlayerResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PlayerRespProto.PlayerResp();
    }

    public static PlayerRespProto.PlayerResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerResp>
        PARSER = new com.google.protobuf.AbstractParser<PlayerResp>() {
      public PlayerResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerResp> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PlayerResp> getParserForType() {
      return PARSER;
    }

    public PlayerRespProto.PlayerResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerResp_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020PlayerResp.proto\"\215\001\n\nPlayerResp\022\021\n\tpla" +
      "yer_id\030\001 \001(\005\022\023\n\013player_name\030\002 \001(\t\022\016\n\006sta" +
      "tus\030\003 \001(\005\022\023\n\013scence_name\030\004 \001(\t\022\021\n\tplayer" +
      "_mp\030\005 \001(\005\022\021\n\tplayer_hp\030\006 \001(\005\022\014\n\004harm\030\007 \001" +
      "(\005B$\n\021com.huyu.protobufB\017PlayerRespProto" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PlayerResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerResp_descriptor,
        new String[] { "PlayerId", "PlayerName", "Status", "ScenceName", "PlayerMp", "PlayerHp", "Harm", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
